<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>IES_2</RootNamespace>
    <AssemblyName>IES_2</AssemblyName>
    <ApplicationIcon>Res\MIL.ico</ApplicationIcon>
    <StartupObject>IES_2.Program</StartupObject>
    <AssemblyTitle>IAW Scan 3</AssemblyTitle>
    <Description>The Marelli IAW x6F/x8F(D) Diagnostic Software for MS Windows</Description>
    <Company>https://github.com/intilinux-eng/iaw-scan-3</Company>
    <Product>IAW Scan 3</Product>
    <Copyright>Copyright © TzOk 2011-2015</Copyright>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZedGraph" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IES_2.Core\IES_2.Core.csproj" />
  </ItemGroup>

</Project>
