<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>IES_2</RootNamespace>
    <AssemblyName>IES_2</AssemblyName>
    <ApplicationIcon>Res\MIL.ico</ApplicationIcon>
    <StartupObject>IES_2.Program</StartupObject>
    <AssemblyTitle>IAW Scan 2</AssemblyTitle>
    <Description>The Marelli IAW x6F/x8F(D) Diagnostic Software for MS Windows</Description>
    <Company>http://iaw-scan2.sourceforge.net</Company>
    <Product>IAW Scan 2</Product>
    <Copyright>Copyright © TzOk 2011-2015</Copyright>
    <AssemblyVersion>0.85.0.0</AssemblyVersion>
    <FileVersion>0.85.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZedGraph" Version="5.2.1" />
    <PackageReference Include="System.IO.Ports" Version="9.0.0" />
  </ItemGroup>

</Project>
