//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES_2.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IES_2.Res.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Relay.
        /// </summary>
        public static string ACrelay {
            get {
                return ResourceManager.GetString("ACrelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A].
        /// </summary>
        public static string Act {
            get {
                return ResourceManager.GetString("Act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Gain Parameter (med. load).
        /// </summary>
        public static string ADGAIN {
            get {
                return ResourceManager.GetString("ADGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADJUSTING: {0}....
        /// </summary>
        public static string Adjusting {
            get {
                return ResourceManager.GetString("Adjusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Offset Parameter (min. load).
        /// </summary>
        public static string ADOFFPL {
            get {
                return ResourceManager.GetString("ADOFFPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Offset Parameter (min. load, EVAP on).
        /// </summary>
        public static string ADOFFPURG {
            get {
                return ResourceManager.GetString("ADOFFPURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Offset Parameter (min. load, EVAP off).
        /// </summary>
        public static string ADOFFSET {
            get {
                return ResourceManager.GetString("ADOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Correction from FLT.
        /// </summary>
        public static string ALFAFTR {
            get {
                return ResourceManager.GetString("ALFAFTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Stepper Motor Position.
        /// </summary>
        public static string ALFAR {
            get {
                return ResourceManager.GetString("ALFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Correction.
        /// </summary>
        public static string ALFAU {
            get {
                return ResourceManager.GetString("ALFAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Correction with A/C.
        /// </summary>
        public static string ALFAUC {
            get {
                return ResourceManager.GetString("ALFAUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle Opening Angle.
        /// </summary>
        public static string ANG_PAP0 {
            get {
                return ResourceManager.GetString("ANG_PAP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above MAX.
        /// </summary>
        public static string AtMAX {
            get {
                return ResourceManager.GetString("AtMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below MIN.
        /// </summary>
        public static string AtMIN {
            get {
                return ResourceManager.GetString("AtMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Detection.
        /// </summary>
        public static string autodetect {
            get {
                return ResourceManager.GetString("autodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition Advance.
        /// </summary>
        public static string AVANCE {
            get {
                return ResourceManager.GetString("AVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELLED.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing error codes....
        /// </summary>
        public static string ClearingErrors {
            get {
                return ResourceManager.GetString("ClearingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil 1.
        /// </summary>
        public static string Coil1 {
            get {
                return ResourceManager.GetString("Coil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil 2.
        /// </summary>
        public static string Coil2 {
            get {
                return ResourceManager.GetString("Coil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ECU Response.
        /// </summary>
        public static string CommLost {
            get {
                return ResourceManager.GetString("CommLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface port ERROR.
        /// </summary>
        public static string COMnotValid {
            get {
                return ResourceManager.GetString("COMnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while openenig the {0} port..
        /// </summary>
        public static string COMopenError {
            get {
                return ResourceManager.GetString("COMopenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Meter.
        /// </summary>
        public static string ConMeter {
            get {
                return ResourceManager.GetString("ConMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTED TO:.
        /// </summary>
        public static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn ON the ignition....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Engine Speed.
        /// </summary>
        public static string CONS_REG {
            get {
                return ResourceManager.GetString("CONS_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Correction (Delta).
        /// </summary>
        public static string DELREG {
            get {
                return ResourceManager.GetString("DELREG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGR Valve.
        /// </summary>
        public static string EGR {
            get {
                return ResourceManager.GetString("EGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the ignition is ON and engine is STOPPED..
        /// </summary>
        public static string EnsureIgnOnEngStop {
            get {
                return ResourceManager.GetString("EnsureIgnOnEngStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocallibration Parameter.
        /// </summary>
        public static string ErrACParam {
            get {
                return ResourceManager.GetString("ErrACParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner.
        /// </summary>
        public static string ErrAirCo {
            get {
                return ResourceManager.GetString("ErrAirCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Transmission.
        /// </summary>
        public static string ErrAutoTrans {
            get {
                return ResourceManager.GetString("ErrAutoTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdoor Acivated.
        /// </summary>
        public static string ErrBackdoor {
            get {
                return ResourceManager.GetString("ErrBackdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Voltage.
        /// </summary>
        public static string ErrBattV {
            get {
                return ResourceManager.GetString("ErrBattV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown CODE ERROR (4).
        /// </summary>
        public static string ErrC4 {
            get {
                return ResourceManager.GetString("ErrC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam sensor.
        /// </summary>
        public static string ErrCam {
            get {
                return ResourceManager.GetString("ErrCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Counter.
        /// </summary>
        public static string ErrCnt {
            get {
                return ResourceManager.GetString("ErrCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition Coil 1.
        /// </summary>
        public static string ErrCoil1 {
            get {
                return ResourceManager.GetString("ErrCoil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition Coil 2.
        /// </summary>
        public static string ErrCoil2 {
            get {
                return ResourceManager.GetString("ErrCoil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Meter.
        /// </summary>
        public static string ErrConMet {
            get {
                return ResourceManager.GetString("ErrConMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string ErrCPU {
            get {
                return ResourceManager.GetString("ErrCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digimatic signal.
        /// </summary>
        public static string ErrDigimatic {
            get {
                return ResourceManager.GetString("ErrDigimatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Temperature Sensor.
        /// </summary>
        public static string ErrECT {
            get {
                return ResourceManager.GetString("ErrECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPROM.
        /// </summary>
        public static string ErrEEPROM {
            get {
                return ResourceManager.GetString("ErrEEPROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGR Control.
        /// </summary>
        public static string ErrEGRCtrl {
            get {
                return ResourceManager.GetString("ErrEGRCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGR Valve.
        /// </summary>
        public static string ErrEGRVal {
            get {
                return ResourceManager.GetString("ErrEGRVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPROM.
        /// </summary>
        public static string ErrEPROM {
            get {
                return ResourceManager.GetString("ErrEPROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVAP Valve.
        /// </summary>
        public static string ErrEVAP {
            get {
                return ResourceManager.GetString("ErrEVAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FUNC ERROR (7).
        /// </summary>
        public static string ErrF7 {
            get {
                return ResourceManager.GetString("ErrF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FUNC ERROR (8).
        /// </summary>
        public static string ErrF8 {
            get {
                return ResourceManager.GetString("ErrF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Pump.
        /// </summary>
        public static string ErrFuelPump {
            get {
                return ResourceManager.GetString("ErrFuelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic System Relay.
        /// </summary>
        public static string ErrGenRel {
            get {
                return ResourceManager.GetString("ErrGenRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown INPUT ERROR (2).
        /// </summary>
        public static string ErrI2 {
            get {
                return ResourceManager.GetString("ErrI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown INPUT ERROR (8).
        /// </summary>
        public static string ErrI8 {
            get {
                return ResourceManager.GetString("ErrI8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Temperature Sensor.
        /// </summary>
        public static string ErrIAT {
            get {
                return ResourceManager.GetString("ErrIAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Stepper Motor.
        /// </summary>
        public static string ErrIAV {
            get {
                return ResourceManager.GetString("ErrIAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Regulation.
        /// </summary>
        public static string ErrIdleReg {
            get {
                return ResourceManager.GetString("ErrIdleReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector.
        /// </summary>
        public static string ErrInj {
            get {
                return ResourceManager.GetString("ErrInj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injectors (group 1).
        /// </summary>
        public static string ErrInj1 {
            get {
                return ResourceManager.GetString("ErrInj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injectors (group 2).
        /// </summary>
        public static string ErrInj2 {
            get {
                return ResourceManager.GetString("ErrInj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injectors.
        /// </summary>
        public static string ErrInjs {
            get {
                return ResourceManager.GetString("ErrInjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Code Error.
        /// </summary>
        public static string ErrKeyCode {
            get {
                return ResourceManager.GetString("ErrKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knocking sensor.
        /// </summary>
        public static string ErrKnock {
            get {
                return ResourceManager.GetString("ErrKnock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knocking Sensor.
        /// </summary>
        public static string ErrKnockS {
            get {
                return ResourceManager.GetString("ErrKnockS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Sensor.
        /// </summary>
        public static string ErrLambda {
            get {
                return ResourceManager.GetString("ErrLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Code Received or Link Down.
        /// </summary>
        public static string ErrLinkDown {
            get {
                return ResourceManager.GetString("ErrLinkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP Sensor.
        /// </summary>
        public static string ErrMAP {
            get {
                return ResourceManager.GetString("ErrMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL Lamp.
        /// </summary>
        public static string ErrMIL {
            get {
                return ResourceManager.GetString("ErrMIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture ratio.
        /// </summary>
        public static string ErrMixRatio {
            get {
                return ResourceManager.GetString("ErrMixRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral/drive signal.
        /// </summary>
        public static string ErrNeutralGear {
            get {
                return ResourceManager.GetString("ErrNeutralGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU not synchronized with CODE.
        /// </summary>
        public static string ErrNoSync {
            get {
                return ResourceManager.GetString("ErrNoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknkown OUTPUT Error (1a).
        /// </summary>
        public static string ErrO1a {
            get {
                return ResourceManager.GetString("ErrO1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknkown OUTPUT Error (2a).
        /// </summary>
        public static string ErrO2a {
            get {
                return ResourceManager.GetString("ErrO2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknkown OUTPUT Error (3a).
        /// </summary>
        public static string ErrO3a {
            get {
                return ResourceManager.GetString("ErrO3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknkown OUTPUT Error (4a).
        /// </summary>
        public static string ErrO4a {
            get {
                return ResourceManager.GetString("ErrO4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORS:.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string ErrRAM {
            get {
                return ResourceManager.GetString("ErrRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM.
        /// </summary>
        public static string ErrROM {
            get {
                return ResourceManager.GetString("ErrROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDC/RPM Sensor.
        /// </summary>
        public static string ErrRPMSens {
            get {
                return ResourceManager.GetString("ErrRPMSens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMOT sensor.
        /// </summary>
        public static string ErrSMOT {
            get {
                return ResourceManager.GetString("ErrSMOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Panel Sequence.
        /// </summary>
        public static string ErrSPS {
            get {
                return ResourceManager.GetString("ErrSPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU Disallowed to Start Engine.
        /// </summary>
        public static string ErrStartDis {
            get {
                return ResourceManager.GetString("ErrStartDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle Position Sensor.
        /// </summary>
        public static string ErrTPS {
            get {
                return ResourceManager.GetString("ErrTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU has received the &apos;Universal Code&apos;.
        /// </summary>
        public static string ErrUniCode {
            get {
                return ResourceManager.GetString("ErrUniCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect or Unrecognized Code.
        /// </summary>
        public static string ErrUnrCode {
            get {
                return ResourceManager.GetString("ErrUnrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAE blocked open or closed.
        /// </summary>
        public static string ErrVAE {
            get {
                return ResourceManager.GetString("ErrVAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Gate.
        /// </summary>
        public static string ErrWasteG {
            get {
                return ResourceManager.GetString("ErrWasteG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Esc] to Cancel.
        /// </summary>
        public static string EscCancel {
            get {
                return ResourceManager.GetString("EscCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVAP Valve.
        /// </summary>
        public static string EVAP {
            get {
                return ResourceManager.GetString("EVAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F10] Connect.
        /// </summary>
        public static string F10_Connect {
            get {
                return ResourceManager.GetString("F10_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F10] Disconnect.
        /// </summary>
        public static string F10_Disconnect {
            get {
                return ResourceManager.GetString("F10_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [F11] to confirm.
        /// </summary>
        public static string F11_Confirm {
            get {
                return ResourceManager.GetString("F11_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Adaptation Activated in EEPROM.
        /// </summary>
        public static string FABEEAT {
            get {
                return ResourceManager.GetString("FABEEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Self-Adaptation Activated in EEPROM.
        /// </summary>
        public static string FABEEATi {
            get {
                return ResourceManager.GetString("FABEEATi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Adaptation Activated in EPROM.
        /// </summary>
        public static string FABEPAT {
            get {
                return ResourceManager.GetString("FABEPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Self-Adaptation Activated in EPROM.
        /// </summary>
        public static string FABEPATi {
            get {
                return ResourceManager.GetString("FABEPATi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda in Closed Loop.
        /// </summary>
        public static string FLGSMA {
            get {
                return ResourceManager.GetString("FLGSMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Pump Relay.
        /// </summary>
        public static string FuelPump {
            get {
                return ResourceManager.GetString("FuelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Relay.
        /// </summary>
        public static string GenericRelay {
            get {
                return ResourceManager.GetString("GenericRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIT. FAIL.
        /// </summary>
        public static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection Timing Angle.
        /// </summary>
        public static string INJ_AVA {
            get {
                return ResourceManager.GetString("INJ_AVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector.
        /// </summary>
        public static string Injector {
            get {
                return ResourceManager.GetString("Injector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector 1.
        /// </summary>
        public static string Injector1 {
            get {
                return ResourceManager.GetString("Injector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector 2.
        /// </summary>
        public static string Injector2 {
            get {
                return ResourceManager.GetString("Injector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector 3.
        /// </summary>
        public static string Injector3 {
            get {
                return ResourceManager.GetString("Injector3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injector 4.
        /// </summary>
        public static string Injector4 {
            get {
                return ResourceManager.GetString("Injector4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injectors.
        /// </summary>
        public static string Injectors {
            get {
                return ResourceManager.GetString("Injectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDING....
        /// </summary>
        public static string InProceed {
            get {
                return ResourceManager.GetString("InProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Stepper Integral Gain.
        /// </summary>
        public static string INTEGR {
            get {
                return ResourceManager.GetString("INTEGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Probe Correction.
        /// </summary>
        public static string K_O2 {
            get {
                return ResourceManager.GetString("K_O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Probe Voltage.
        /// </summary>
        public static string K_O2_RAW {
            get {
                return ResourceManager.GetString("K_O2_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max LEAN.
        /// </summary>
        public static string MaxLEAN {
            get {
                return ResourceManager.GetString("MaxLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max RICH.
        /// </summary>
        public static string MaxRICH {
            get {
                return ResourceManager.GetString("MaxRICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL Lamp.
        /// </summary>
        public static string MIL {
            get {
                return ResourceManager.GetString("MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifold Absolute Pressure.
        /// </summary>
        public static string MP2_MP8 {
            get {
                return ResourceManager.GetString("MP2_MP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifold Absolute Pressure (TURBO).
        /// </summary>
        public static string MP2_MP8t {
            get {
                return ResourceManager.GetString("MP2_MP8t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Temperature.
        /// </summary>
        public static string MT_AIR_L {
            get {
                return ResourceManager.GetString("MT_AIR_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Temperature.
        /// </summary>
        public static string MT_EAU_L {
            get {
                return ResourceManager.GetString("MT_EAU_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Air.
        /// </summary>
        public static string NoAir {
            get {
                return ResourceManager.GetString("NoAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 1.
        /// </summary>
        public static string OFFSET1 {
            get {
                return ResourceManager.GetString("OFFSET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 2.
        /// </summary>
        public static string OFFSET2 {
            get {
                return ResourceManager.GetString("OFFSET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 3.
        /// </summary>
        public static string OFFSET3 {
            get {
                return ResourceManager.GetString("OFFSET3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 4.
        /// </summary>
        public static string OFFSET4 {
            get {
                return ResourceManager.GetString("OFFSET4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 5.
        /// </summary>
        public static string OFFSET5 {
            get {
                return ResourceManager.GetString("OFFSET5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ ZONE 6.
        /// </summary>
        public static string OFFSET6 {
            get {
                return ResourceManager.GetString("OFFSET6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocalibration Injection Offset @ IDLE.
        /// </summary>
        public static string OFFSETm {
            get {
                return ResourceManager.GetString("OFFSETm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Engine Speed Offset.
        /// </summary>
        public static string OFNNTR {
            get {
                return ResourceManager.GetString("OFNNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Circuit.
        /// </summary>
        public static string OpenCircuit {
            get {
                return ResourceManager.GetString("OpenCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Boost.
        /// </summary>
        public static string OverB {
            get {
                return ResourceManager.GetString("OverB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETERS:.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Speed.
        /// </summary>
        public static string PERIODE {
            get {
                return ResourceManager.GetString("PERIODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [F10] to close connection or [F12] to try to reconnect.
        /// </summary>
        public static string Press_F10 {
            get {
                return ResourceManager.GetString("Press_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously selected port {0} is no longer available. Please select another port..
        /// </summary>
        public static string PreviouslySelectedPort {
            get {
                return ResourceManager.GetString("PreviouslySelectedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Stepper Proportional Gain.
        /// </summary>
        public static string PROP {
            get {
                return ResourceManager.GetString("PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REV Meter.
        /// </summary>
        public static string REVmeter {
            get {
                return ResourceManager.GetString("REVmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string rpm {
            get {
                return ResourceManager.GetString("rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short to GND.
        /// </summary>
        public static string ShortToGND {
            get {
                return ResourceManager.GetString("ShortToGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short to GND/Open.
        /// </summary>
        public static string ShortToGNDorOpen {
            get {
                return ResourceManager.GetString("ShortToGNDorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short to +Vcc.
        /// </summary>
        public static string ShortToVcc {
            get {
                return ResourceManager.GetString("ShortToVcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMULATION MODE!!!.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS active.
        /// </summary>
        public static string StaABSON {
            get {
                return ResourceManager.GetString("StaABSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignition Advance Decrased for Knocking.
        /// </summary>
        public static string StaAdvDecr {
            get {
                return ResourceManager.GetString("StaAdvDecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner ON.
        /// </summary>
        public static string StaAirCoON {
            get {
                return ResourceManager.GetString("StaAirCoON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Sensor in Closed Loop.
        /// </summary>
        public static string StaClLoop {
            get {
                return ResourceManager.GetString("StaClLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Running.
        /// </summary>
        public static string StaEngRun {
            get {
                return ResourceManager.GetString("StaEngRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Engaged.
        /// </summary>
        public static string StaGearEng {
            get {
                return ResourceManager.GetString("StaGearEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixture AutoCalibration ENABLED.
        /// </summary>
        public static string StaMixACOK {
            get {
                return ResourceManager.GetString("StaMixACOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Latch Line OK.
        /// </summary>
        public static string StaPLatchOK {
            get {
                return ResourceManager.GetString("StaPLatchOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Signals OK.
        /// </summary>
        public static string StaSensOK {
            get {
                return ResourceManager.GetString("StaSensOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal panel OK.
        /// </summary>
        public static string StaSigPanOK {
            get {
                return ResourceManager.GetString("StaSigPanOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper AutoCalibration ENABLED.
        /// </summary>
        public static string StaStepACOK {
            get {
                return ResourceManager.GetString("StaStepACOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle at Min/Max.
        /// </summary>
        public static string StaThrMM {
            get {
                return ResourceManager.GetString("StaThrMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAE Self Cleaning underway.
        /// </summary>
        public static string StaVAESC {
            get {
                return ResourceManager.GetString("StaVAESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper motor (idle actuator).
        /// </summary>
        public static string Stepper {
            get {
                return ResourceManager.GetString("Stepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle stepper autocalibration reset.
        /// </summary>
        public static string StepReset {
            get {
                return ResourceManager.GetString("StepReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steps.
        /// </summary>
        public static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set stepper correction (ALFAFTR).
        /// </summary>
        public static string StepSet {
            get {
                return ResourceManager.GetString("StepSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [S].
        /// </summary>
        public static string Sto {
            get {
                return ResourceManager.GetString("Sto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection Duration.
        /// </summary>
        public static string T_INJ_AP {
            get {
                return ResourceManager.GetString("T_INJ_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAE Duty Cycle (Idle Control).
        /// </summary>
        public static string T_VAE {
            get {
                return ResourceManager.GetString("T_VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If test takes longer than {0}s please turn ignition OFF and close the application!.
        /// </summary>
        public static string TestDuration {
            get {
                return ResourceManager.GetString("TestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTING: {0}....
        /// </summary>
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short to GND/+Vcc/Therm.
        /// </summary>
        public static string Therm {
            get {
                return ResourceManager.GetString("Therm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMEOUT.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle idle stepper autocalibration.
        /// </summary>
        public static string ToggleStepAC {
            get {
                return ResourceManager.GetString("ToggleStepAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fuel trim autocalibration.
        /// </summary>
        public static string ToggleTrimAC {
            get {
                return ResourceManager.GetString("ToggleTrimAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Much Air.
        /// </summary>
        public static string TooMuchAir {
            get {
                return ResourceManager.GetString("TooMuchAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmer Position.
        /// </summary>
        public static string TRIMRAM {
            get {
                return ResourceManager.GetString("TRIMRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel trim autocalibration reset.
        /// </summary>
        public static string TrimReset {
            get {
                return ResourceManager.GetString("TrimReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set trimmer position (TRIMRAM).
        /// </summary>
        public static string TrimSet {
            get {
                return ResourceManager.GetString("TrimSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn OFF the ignition....
        /// </summary>
        public static string TurnOFF {
            get {
                return ResourceManager.GetString("TurnOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownISO {
            get {
                return ResourceManager.GetString("UnknownISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU could not be recognized, please turn OFF the ignition....
        /// </summary>
        public static string UnrecECU {
            get {
                return ResourceManager.GetString("UnrecECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Voltage.
        /// </summary>
        public static string V_BATT {
            get {
                return ResourceManager.GetString("V_BATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Control Valve (VAE).
        /// </summary>
        public static string VAE {
            get {
                return ResourceManager.GetString("VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [V].
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES;;NO.
        /// </summary>
        public static string yes_no {
            get {
                return ResourceManager.GetString("yes_no", resourceCulture);
            }
        }
    }
}
